const MessageType =  {
    "QUERY_LATEST": "QUERY_LATEST",
    "RESPONSE_LASTBLOCK":"RESPONSE_LASTBLOCK",
    "QUERY_ALL":"QUERY_ALL",
    "RESPONSE_BLOCKCHAIN":"RESPONSE_BLOCKCHAIN",
    "QUERY_TRANSACTION_POOL":"QUERY_TRANSACTION_POOL",
    "RESPONSE_TRANSACTION_POOL": "RESPONSE_TRANSACTION_POOL",
    "ADD_TRANSACTION_TO_POOL": "ADD_TRANSACTION_TO_POOL",
    "REMOVE_TRANSACTION_FROM_POOL": "REMOVE_TRANSACTION_FROM_POOL",
}

module.exports = {
    MessageType
}